package com.java.main.interfaces;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;

import com.java.main.beans.ColSummary;

public interface IBusinessRule {

	/**
	 * 
	 * @param colSummary
	 *            will be containing column names as key and their summary as
	 *            the value of the HashMap
	 * @param numRows
	 *            will be numbers of rows
	 */

	public void genrateRule(LinkedHashMap<String, ColSummary> colSummary,
			int numRows);
	
	
	public String toString();
	
	/**
	 * 
	 * @return Rules generated by respective class
	 */
	public ArrayList<String> getRules();
	
	/**
	 * 
	 * @param HashSet of colNames which are selected by the user
	 * @return Rules generated by respective class after filtering on the selected colNames
	 */
	public ArrayList<String> getFilteredRules(HashSet<String> colNames);
	
}
